final Map<String, String> ar = {
  'settings': 'الإعدادات',
  'child_profile': 'الملف الشخصي للطفل',
  'rate_improvement': 'معدل التحسن',
  'national_number': 'الرقم الوطني',
  'add_child': 'اضف طفل',
  'logout': 'تسجيل الخروج',
  'login': 'تسجيل الدخول',
  'Add a dose of insulin': 'اضف جرعة الانسولين',
  'Manage your insuline dose': 'إدارة جرعة الأنسولين الخاصة بك',
  'There is a child already registered with this national number':
      'يوجد طفل مسجل بهذا الرقم الوطني مسبقًا',
  'Enter your childs national number': 'ادخل الرقم الوطني الخاص في طفلك',
  'National ID found, but no child data':
      'تم العثور على الرقم الوطني، ولكن لا يوجد بيانات الطفل.',
  'sign_in_to_continue': 'سجل الدخول للمتابعة',
  'Not Found': 'لا يوجد طفل بهذا الرقم الوطني',
  'success': 'تم',
  'Add Dose': 'اضف جرعة',
  'The child has been successfully added to your account':
      'تم إضافة الطفل إلى حسابك بنجاح',
  'Already exists': 'موجود مسبقا',
  'This child has already been added to your account':
      'تم إضافة هذا الطفل سابقاً إلى حسابك',
  'email': 'البريد الإلكتروني',
  'enter_email': 'أدخل البريد الإلكتروني',
  'password': 'كلمة المرور',
  'enter_password': 'أدخل كلمة المرور',
  'dont_have_account': 'ليس لديك حساب؟',
  'sign_up': 'سجل الآن',
  'back': 'رجوع',
  'who_am_i': 'من أنا؟',
  'parent': 'الأب',
  'caregiver': 'مقدم الرعاية',
  'please_choose_one': 'يرجى اختيار أحدهم',
  'ok': 'موافق',
  'next': 'التالي',
  'app_name': 'سكر',
  'child_nickname': 'اسم الطفل المستعار',
  'chat': 'الدردشة',
  'chatbot': 'روبوت الدردشة',
  'medications': 'الأدوية',
  'exercise': 'التمرينات',
  'meals': 'الوجبات',
  'emergency_instructions': 'تعليمات الطوارئ',
  'welcome_user': 'مرحبًا، المستخدم!',
  'profile': 'الملف الشخصي',
  'theme': 'السمة',
  'privacy': 'الخصوصية',
  'language': 'اللغة',
  'manage_profile': 'إدارة ملفك الشخصي',
  'manage_medications': 'إدارة الأدوية',
  'manage_meals': 'إدارة الوجبات',
  'switch_theme': 'التبديل بين الوضع الفاتح والداكن',
  'manage_privacy': 'إدارة إعدادات الخصوصية',
  'select_language': 'اختيار اللغة',
  'translation_settings': 'إعدادات الترجمة',
  'english': 'الإنجليزية',
  'arabic': 'العربية',
  "FirstName": "الاسم الأول",
  "EnterYourName": "أدخل اسمك الأول",
  "LastName": "الاسم الأخير",
  "Email": "البريد الإلكتروني",
  "EnterEmail": "أدخل بريدك الإلكتروني",
  "Password": "كلمة المرور",
  "EnterPassword": "أدخل كلمة المرور",
  "ConfirmPassword": "تأكيد كلمة المرور",
  "ReenterPassword": "أعد إدخال كلمة المرور",
  "Next": "التالي",
  "Back": "رجوع",
  "Answer these questions about your child": "أجب عن هذه الأسئلة حول طفلك",
  "Name": "الاسم",
  "Enter name": "أدخل الاسم",
  "Gender": "الجنس",
  "Male": "ذكر",
  "Female": "أنثى",
  "Type of diabetes": "نوع السكري",
  "Age": "العمر",
  "Enter age": "أدخل العمر",
  "Height": "الطول",
  "Enter height": "أدخل الطول",
  "Weight": "الوزن",
  "Enter weight": "أدخل الوزن",
  "Please fill all the fields": "يرجى ملء جميع الحقول",
  "Your child's profile": "ملف طفلك",
  "Enter your name": "أدخل اسمك",
  "Child's picture": "صورة الطفل",
  "Sukr": "سكر",
  "Share access to\nyour child’s profile": "مشاركة الوصول إلى\nملف طفلك",
  "Your child link": "رابط طفلك",
  "Copy link": "نسخ الرابط",
  'edit': 'تعديل',
  'backpack': 'الحقيبة',
  'emergency_cases': 'حالات الطوارئ',
  'low_blood_sugar': 'انخفاض سكر الدم',
  'high_blood_sugar': 'ارتفاع سكر الدم',
  'loss_of_consciousness': 'فقدان الوعي',
  'request_for_help': 'طلب المساعدة',
  "🩸 What is Low Blood Sugar?": "🩸 ما هو انخفاض سكر الدم؟",
  "Low blood sugar (hypoglycemia) occurs when blood sugar levels drop below the normal range (usually under 70 mg/dL). This can happen for various reasons, such as taking too much insulin, skipping meals, or excessive exercise.":
      "يحدث انخفاض سكر الدم (نقص السكر) عندما تنخفض مستويات السكر عن المعدل الطبيعي (عادةً أقل من 70 ملغم/ديسيلتر). يمكن أن يحدث ذلك لأسباب مثل تناول الكثير من الإنسولين، أو تخطي الوجبات، أو ممارسة التمارين بشكل مفرط.",
  "⚠️ Symptoms:": "⚠️ الأعراض:",
  "Shaking and trembling": "الارتعاش والرعشة",
  "Sweating": "التعرق",
  "Dizziness or lightheadedness": "الدوخة أو الشعور بخفة الرأس",
  "Intense hunger": "جوع شديد",
  "Fatigue or irritability": "التعب أو الانفعال",
  "🚨 What to do in case of Low Blood Sugar:":
      "🚨 ماذا تفعل في حالة انخفاض سكر الدم:",
  "1. Give 15 grams of fast-acting sugar (e.g., half a cup of juice, 1 tablespoon of honey, or 3-4 glucose tablets).":
      "1. أعطِ 15 غرامًا من السكر سريع المفعول (مثل نصف كوب عصير، ملعقة عسل، أو 3-4 أقراص جلوكوز).",
  "2. Wait for 15 minutes and recheck the blood sugar.":
      "2. انتظر 15 دقيقة ثم أعد فحص السكر.",
  "3. If blood sugar is still low, repeat the 15 grams of sugar.":
      "3. إذا استمر انخفاض السكر، كرر إعطاء 15 غرامًا من السكر.",
  "4. After recovery, give a balanced meal with carbs and protein.":
      "4. بعد التعافي، قدم وجبة متوازنة تحتوي على كربوهيدرات وبروتين.",
  "📞 If the person is unconscious, **do not give anything to eat or drink**, and immediately call emergency services.":
      "📞 إذا كان الشخص فاقدًا للوعي، **لا تعطه أي طعام أو شراب**، واتصل فورًا بالطوارئ.",
  "Go Back": "رجوع",
  "🔥 What is High Blood Sugar?": "🔥 ما هو ارتفاع سكر الدم؟",
  "High blood sugar (hyperglycemia) occurs when blood sugar levels are too high (above 180 mg/dL after meals). It may result from missed insulin doses, consuming too much food, stress, or illness.":
      "يحدث ارتفاع سكر الدم (فرط السكر) عندما تكون مستويات السكر في الدم مرتفعة جدًا (أعلى من 180 ملغم/ديسيلتر بعد الوجبات). قد يحدث بسبب نسيان جرعة الإنسولين، أو تناول كميات كبيرة من الطعام، أو التوتر، أو المرض.",
  "Frequent urination": "التبول المتكرر",
  "Increased thirst": "العطش الشديد",
  "Blurred vision": "تشوش الرؤية",
  "Fatigue": "التعب",
  "Headache": "الصداع",
  "🚨 What to do in case of High Blood Sugar:":
      "🚨 ماذا تفعل في حالة ارتفاع سكر الدم:",
  "1. Administer insulin as prescribed.": "1. تناول الإنسولين حسب التعليمات.",
  "2. Drink water to stay hydrated.": "2. اشرب الماء للبقاء رطبًا.",
  "3. Avoid carbohydrate-rich foods.": "3. تجنب الأطعمة الغنية بالكربوهيدرات.",
  "4. Monitor blood sugar closely.": "4. راقب مستوى السكر في الدم بدقة.",
  "5. Seek medical attention if symptoms worsen.":
      "5. اطلب العناية الطبية إذا ساءت الأعراض.",
  "🧠 What is Loss of Consciousness?": "🧠 ما هو فقدان الوعي؟",
  "Loss of consciousness occurs when a person is unable to respond to people or activities. It can be caused by low blood sugar, head trauma, or other medical emergencies.":
      "يحدث فقدان الوعي عندما لا يستطيع الشخص الاستجابة للأشخاص أو الأنشطة. وقد يكون سببه انخفاض السكر في الدم أو إصابة في الرأس أو حالات طبية طارئة أخرى.",
  "⚠️ Signs and Symptoms:": "⚠️ العلامات والأعراض:",
  "No response to voice or touch": "لا يستجيب للصوت أو اللمس",
  "Slow or irregular breathing": "تنفس بطيء أو غير منتظم",
  "Pale or bluish skin": "جلد شاحب أو مائل للزرقة",
  "Weak or no pulse": "نبض ضعيف أو غير موجود",
  "🚨 What to do in this situation:": "🚨 ماذا تفعل في هذه الحالة:",
  "1. Check for breathing and pulse.": "1. تحقق من التنفس والنبض.",
  "2. Call emergency services immediately.": "2. اتصل بخدمات الطوارئ فوراً.",
  "3. If trained, begin CPR if no pulse is found.":
      "3. إذا كنت مدربًا، ابدأ الإنعاش القلبي الرئوي إذا لم يكن هناك نبض.",
  "4. If the person is breathing, place them in the recovery position.":
      "4. إذا كان الشخص يتنفس، ضعه في وضعية التعافي.",
  "📞 Requesting Help in Emergencies": "📞 طلب المساعدة في حالات الطوارئ",
  "Knowing when and how to request help during a medical emergency can save lives. Whether it's contacting emergency services or notifying someone nearby, it's important to act quickly and clearly.":
      "معرفة متى وكيف تطلب المساعدة أثناء حالة طبية طارئة قد تنقذ الأرواح. سواء كان ذلك عن طريق الاتصال بخدمات الطوارئ أو تنبيه شخص قريب، من المهم التصرف بسرعة ووضوح.",
  "🆘 When to Call for Help:": "🆘 متى يجب طلب المساعدة:",
  "Loss of consciousness": "فقدان الوعي",
  "Severe difficulty breathing": "صعوبة شديدة في التنفس",
  "Uncontrollable bleeding": "نزيف لا يمكن السيطرة عليه",
  "Seizures or convulsions": "نوبات أو تشنجات",
  "Confusion or disorientation": "ارتباك أو تشوش",
  "📲 How to Request Help:": "📲 كيفية طلب المساعدة:",
  "1. Dial the local emergency number (e.g., 911).":
      "1. اتصل برقم الطوارئ المحلي (مثل 911).",
  "2. Clearly state your location and the nature of the emergency.":
      "2. حدد موقعك وطبيعة الحالة الطارئة بوضوح.",
  "3. Stay on the line until help arrives or the operator says you can hang up.":
      "3. ابقَ على الخط حتى تصل المساعدة أو يُطلب منك إنهاء المكالمة.",
  "4. If possible, alert others nearby for assistance.":
      "4. إذا أمكن، نبه من حولك للمساعدة.",
  "Manage Your Meals": "إدارة وجباتك",
  "Meal Name": "اسم الوجبة",
  "Enter meal name": "أدخل اسم الوجبة",
  "Meal Time": "وقت الوجبة",
  "Tap to pick time": "اضغط لاختيار الوقت",
  "Description": "الوصف",
  "Short description": "وصف مختصر",
  "Add Meal": "إضافة وجبة",
  "Meal added successfully": "تمت إضافة الوجبة بنجاح",
  "Meals List": "قائمة الوجبات",
  "Delete Meal": "حذف الوجبة",
  "Are you sure you want to delete this meal?":
      "هل أنت متأكد أنك تريد حذف هذه الوجبة؟",
  "Cancel": "إلغاء",
  "Delete": "حذف",
  "Manage Your Medications": "إدارة أدويتك",
  "Medication Name": "اسم الدواء",
  "Enter medication name": "أدخل اسم الدواء",
  "Dose (e.g. 500mg)": "الجرعة (مثلاً 500ملغ)",
  "Enter dose": "أدخل الجرعة",
  "Time to Take": "وقت التناول",
  "e.g. Morning, Evening": "مثلاً صباحًا، مساءً",
  "Add Medication": "إضافة دواء",
  "Medication added successfully": "تمت إضافة الدواء بنجاح",
  "Medications List": "قائمة الأدوية",
  "No medications added yet.": "لم تتم إضافة أي أدوية بعد.",

  "Privacy Policy": "سياسة الخصوصية",
  "Your Privacy Matters": "خصوصيتك تهمنا",
  "We are committed to protecting your privacy. This Privacy Policy outlines how we collect, use, and safeguard your information.":
      "نحن ملتزمون بحماية خصوصيتك. توضح سياسة الخصوصية هذه كيفية جمع معلوماتك واستخدامها وحمايتها.",
  "1. Information Collection": "1. جمع المعلومات",
  "We collect data you provide, such as your name, email, and health information, to improve your experience.":
      "نقوم بجمع البيانات التي تقدمها، مثل الاسم والبريد الإلكتروني والمعلومات الصحية، لتحسين تجربتك.",
  "2. How We Use Your Data": "2. كيفية استخدام بياناتك",
  "Your data is used solely for enhancing the features of the app, ensuring personalized content and support.":
      "تُستخدم بياناتك فقط لتعزيز ميزات التطبيق، وضمان محتوى ودعم مخصص لك.",
  "3. Data Protection": "3. حماية البيانات",
  "We implement strict security measures to ensure the safety of your personal data.":
      "نطبق إجراءات أمان صارمة لضمان سلامة بياناتك الشخصية.",
  "4. Your Consent": "4. موافقتك",
  "By using our app, you consent to this Privacy Policy.":
      "باستخدامك للتطبيق، فإنك توافق على سياسة الخصوصية هذه.",
  "5. Changes to Policy": "5. التغييرات على السياسة",
  "We may update this policy periodically. Please review it regularly for changes.":
      "قد نقوم بتحديث هذه السياسة بشكل دوري. يرجى مراجعتها بانتظام لمعرفة أي تغييرات.",
  "Personal Account Settings": "إعدادات الحساب الشخصي",
  "Full Name": "الاسم الكامل",
  "Enter your full name": "أدخل اسمك الكامل",
  "Email Address": "البريد الإلكتروني",
  "Enter your email address": "أدخل بريدك الإلكتروني",
  "Phone Number": "رقم الهاتف",
  "Enter your phone number": "أدخل رقم هاتفك",
  "Change Password": "تغيير كلمة المرور",
  "Update your account password": "قم بتحديث كلمة المرور الخاصة بك",
  "Deactivate Account": "إلغاء تنشيط الحساب",
  "Temporarily deactivate your account": "قم بإلغاء تنشيط حسابك مؤقتًا",
  "Save Changes": "حفظ التغييرات",
  "Current Password": "كلمة المرور الحالية",
  "Enter current password": "أدخل كلمة المرور الحالية",
  "New Password": "كلمة المرور الجديدة",
  "Enter new password": "أدخل كلمة المرور الجديدة",
  "Confirm New Password": "تأكيد كلمة المرور الجديدة",
  "Confirm new password": "أعد إدخال كلمة المرور الجديدة",
  "Update Password": "تحديث كلمة المرور",
  "Password updated successfully": "تم تحديث كلمة المرور بنجاح",
  "Passwords do not match": "كلمتا المرور غير متطابقتين",
  "Reactivate Account": "إعادة تفعيل الحساب",
  "Are you sure?": "هل أنت متأكد؟",
  "Your account will be temporarily deactivated.": "سيتم تعطيل حسابك مؤقتًا.",
  "Deactivate": "تعطيل",
  "Account deactivated": "تم تعطيل الحساب",
  "Do you want to reactivate your account?": "هل ترغب في إعادة تفعيل حسابك؟",
  "Reactivate": "إعادة تفعيل",
  "Account reactivated": "تم تفعيل الحساب",
  "Are you sure you want to deactivate your account?":
      "هل أنت متأكد أنك تريد تعطيل حسابك؟",
  "This will temporarily disable your account and you won't be able to access any features until you reactivate it.":
      "سيؤدي ذلك إلى تعطيل حسابك مؤقتًا ولن تتمكن من استخدام أي ميزة حتى تقوم بإعادة تفعيله.",
  "Child's Personal Profile": "الملف الشخصي للطفل",
  "Child's Full Name": "الاسم الكامل للطفل",
  "Enter child's full name": "أدخل الاسم الكامل للطفل",
  "Date of Birth": "تاريخ الميلاد",
  "Enter child's date of birth": "أدخل تاريخ ميلاد الطفل",
  "Select gender": "اختر الجنس",
  "Select Gender": "اختر الجنس",
  "Child's Profile Link": "رابط ملف الطفل",
  "Enter child's profile link": "أدخل رابط ملف الطفل",
  "Link copied to clipboard": "تم نسخ الرابط إلى الحافظة",
  "Profile updated successfully": "تم تحديث الملف الشخصي بنجاح",
  "Who am i?": "من أنا؟",
  "Parent": "أب/أم",
  "Caregiver": "مقدم رعاية",
  "Please choose one of them": "يرجى اختيار أحد الخيارين",
  "Ok": "موافق",
  "Parents": "الوالدين",
  "Input glucose level before activity": "أدخل مستوى الجلوكوز قبل النشاط",
  "Input glucose level after activity": "إدخال مستوى الجلوكوز بعد النشاط",
  "Duration of the activity": "مدة النشاط",
  "Minutes": "الدقائق",
  "High intensity exercises": "تمارين عالية الكثافة",
  "Average running": "تمارين متوسط",
  "Light walking": "المشي الخفيف",
  "Type of activity (MET)": "نوع النشاط (MET)",
  "Weight(Kg)": "الوزن",
  "Calculate": "حساب",
  "Insulin Reduction": "تخفيض الأنسولين",
  "Glucose Reduction Percentage": "نسبة انخفاض الجلوكوز",
  "Carbohydrates needed (grams)": "الكربوهيدرات المطلوبة (جرام)",
  "Back to home": "الرجوع الى الرئيسية",
};
