final Map<String, String> en = {
  'settings': 'Settings',
  'child_profile': 'Child’s Personal\nProfile',
  'rate_improvement': 'Rate of\nImprovement',
  'logout': 'Log Out',
  'login': 'Login',
  'sign_in_to_continue': 'Sign in to continue',
  'email': 'Email',
  'enter_email': 'Enter your email',
  'password': 'Password',
  'enter_password': 'Enter your password',
  'dont_have_account': 'Don’t have an account?',
  'sign_up': 'Sign Up',
  'national_number': 'National Number',
  'add_child': 'Add child',
  'back': 'Back',
  'who_am_i': 'Who am I?',
  'National ID found, but no child data':
      'National ID found, but no child data',
  'Not Found': 'No child exists with this national number',
  'parent': 'Parent',
  'There is a child already registered with this national number':
      'There is a child already registered with this national number',
  'Enter your childs national number': 'Enter your childs national number',
  'caregiver': 'Caregiver',
  'done': 'Done',
  'please_choose_one': 'Please choose one',
  'The child has been successfully added to your account':
      'The child has been successfully added to your account',
  'ok': 'OK',
  'Already exists': 'Already exists',
  'This child has already been added to your account':
      'This child has already been added to your account',
  'next': 'Next',
  'Add a dose of insulin': 'Add a dose of insulin',
  'Manage your insuline dose': 'Manage Your Insuline Dose',
  'app_name': 'Sukr',
  'Add Dose': 'Add Dose',
  'child_nickname': 'Child Nickname',
  'chat': 'Chat',
  'chatbot': 'Chatbot',
  'medications': 'Medications',
  'exercise': 'Exercise',
  'meals': 'Meals',
  'emergency_instructions': 'Emergency Instructions',
  'welcome_user': 'Welcome, User!',
  'profile': 'Profile',
  'theme': 'Theme',
  'privacy': 'Privacy',
  'language': 'Language',
  'manage_profile': 'Manage your profile',
  'manage_medications': 'Manage medications',
  'manage_meals': 'Manage meals',
  'switch_theme': 'Switch between light and dark mode',
  'manage_privacy': 'Manage privacy settings',
  'select_language': 'Select Language',
  'translation_settings': 'Translation Settings',
  'english': 'English',
  'arabic': 'Arabic',
  "FirstName": "First Name",
  "EnterYourName": "Enter your first name",
  "LastName": "Last Name",
  "Email": "Email",
  "EnterEmail": "Enter your email",
  "Password": "Password",
  "EnterPassword": "Enter a password",
  "ConfirmPassword": "Confirm Password",
  "ReenterPassword": "Re-enter password",
  "Next": "Next",
  "Back": "Back",
  "Answer these questions about your child":
      "Answer these questions about your child",
  "Name": "Name",
  "Enter name": "Enter name",
  "Gender": "Gender",
  "Male": "Male",
  "Female": "Female",
  "Type of diabetes": "Type of diabetes",
  "Age": "Age",
  "Enter age": "Enter age",
  "Height": "Height",
  "Enter height": "Enter height",
  "Weight": "Weight",
  "Enter weight": "Enter weight",
  "Please fill all the fields": "Please fill all the fields",
  "Your child's profile": "Your child's profile",
  "Enter your name": "Enter your name",
  "Child's picture": "Child's picture",
  "Sukr": "Sukr",
  "Share access to\nyour child’s profile":
      "Share access to\nyour child’s profile",
  "Your child link": "Your child link",
  "Copy link": "Copy link",
  "edit": 'Edit',
  "backpack": 'Backpack',
  'emergency_cases': 'Emergency Cases',
  'low_blood_sugar': 'Low Blood Sugar',
  'high_blood_sugar': 'High Blood Sugar',
  'loss_of_consciousness': 'Loss of Consciousness',
  'request_for_help': 'Request for Help',
  "🩸 What is Low Blood Sugar?": "🩸 What is Low Blood Sugar?",
  "Low blood sugar (hypoglycemia) occurs when blood sugar levels drop below the normal range (usually under 70 mg/dL). This can happen for various reasons, such as taking too much insulin, skipping meals, or excessive exercise.":
      "Low blood sugar (hypoglycemia) occurs when blood sugar levels drop below the normal range (usually under 70 mg/dL). This can happen for various reasons, such as taking too much insulin, skipping meals, or excessive exercise.",
  "⚠️ Symptoms:": "⚠️ Symptoms:",
  "Shaking and trembling": "Shaking and trembling",
  "Sweating": "Sweating",
  "Dizziness or lightheadedness": "Dizziness or lightheadedness",
  "Intense hunger": "Intense hunger",
  "Fatigue or irritability": "Fatigue or irritability",
  "🚨 What to do in case of Low Blood Sugar:":
      "🚨 What to do in case of Low Blood Sugar:",
  "1. Give 15 grams of fast-acting sugar (e.g., half a cup of juice, 1 tablespoon of honey, or 3-4 glucose tablets).":
      "1. Give 15 grams of fast-acting sugar (e.g., half a cup of juice, 1 tablespoon of honey, or 3-4 glucose tablets).",
  "2. Wait for 15 minutes and recheck the blood sugar.":
      "2. Wait for 15 minutes and recheck the blood sugar.",
  "3. If blood sugar is still low, repeat the 15 grams of sugar.":
      "3. If blood sugar is still low, repeat the 15 grams of sugar.",
  "4. After recovery, give a balanced meal with carbs and protein.":
      "4. After recovery, give a balanced meal with carbs and protein.",
  "📞 If the person is unconscious, **do not give anything to eat or drink**, and immediately call emergency services.":
      "📞 If the person is unconscious, **do not give anything to eat or drink**, and immediately call emergency services.",
  "Go Back": "Go Back",
  "🔥 What is High Blood Sugar?": "🔥 What is High Blood Sugar?",
  "High blood sugar (hyperglycemia) occurs when blood sugar levels are too high (above 180 mg/dL after meals). It may result from missed insulin doses, consuming too much food, stress, or illness.":
      "High blood sugar (hyperglycemia) occurs when blood sugar levels are too high (above 180 mg/dL after meals). It may result from missed insulin doses, consuming too much food, stress, or illness.",
  "Frequent urination": "Frequent urination",
  "Increased thirst": "Increased thirst",
  "Blurred vision": "Blurred vision",
  "Fatigue": "Fatigue",
  "Headache": "Headache",
  "🚨 What to do in case of High Blood Sugar:":
      "🚨 What to do in case of High Blood Sugar:",
  "1. Administer insulin as prescribed.":
      "1. Administer insulin as prescribed.",
  "2. Drink water to stay hydrated.": "2. Drink water to stay hydrated.",
  "3. Avoid carbohydrate-rich foods.": "3. Avoid carbohydrate-rich foods.",
  "4. Monitor blood sugar closely.": "4. Monitor blood sugar closely.",
  "5. Seek medical attention if symptoms worsen.":
      "5. Seek medical attention if symptoms worsen.",
  "🧠 What is Loss of Consciousness?": "🧠 What is Loss of Consciousness?",
  "Loss of consciousness occurs when a person is unable to respond to people or activities. It can be caused by low blood sugar, head trauma, or other medical emergencies.":
      "Loss of consciousness occurs when a person is unable to respond to people or activities. It can be caused by low blood sugar, head trauma, or other medical emergencies.",
  "⚠️ Signs and Symptoms:": "⚠️ Signs and Symptoms:",
  "No response to voice or touch": "No response to voice or touch",
  "Slow or irregular breathing": "Slow or irregular breathing",
  "Pale or bluish skin": "Pale or bluish skin",
  "Weak or no pulse": "Weak or no pulse",
  "🚨 What to do in this situation:": "🚨 What to do in this situation:",
  "1. Check for breathing and pulse.": "1. Check for breathing and pulse.",
  "2. Call emergency services immediately.":
      "2. Call emergency services immediately.",
  "3. If trained, begin CPR if no pulse is found.":
      "3. If trained, begin CPR if no pulse is found.",
  "4. If the person is breathing, place them in the recovery position.":
      "4. If the person is breathing, place them in the recovery position.",
  "📞 Requesting Help in Emergencies": "📞 Requesting Help in Emergencies",
  "Knowing when and how to request help during a medical emergency can save lives. Whether it's contacting emergency services or notifying someone nearby, it's important to act quickly and clearly.":
      "Knowing when and how to request help during a medical emergency can save lives. Whether it's contacting emergency services or notifying someone nearby, it's important to act quickly and clearly.",
  "🆘 When to Call for Help:": "🆘 When to Call for Help:",
  "Loss of consciousness": "Loss of consciousness",
  "Severe difficulty breathing": "Severe difficulty breathing",
  "Uncontrollable bleeding": "Uncontrollable bleeding",
  "Seizures or convulsions": "Seizures or convulsions",
  "Confusion or disorientation": "Confusion or disorientation",
  "📲 How to Request Help:": "📲 How to Request Help:",
  "1. Dial the local emergency number (e.g., 911).":
      "1. Dial the local emergency number (e.g., 911).",
  "2. Clearly state your location and the nature of the emergency.":
      "2. Clearly state your location and the nature of the emergency.",
  "3. Stay on the line until help arrives or the operator says you can hang up.":
      "3. Stay on the line until help arrives or the operator says you can hang up.",
  "4. If possible, alert others nearby for assistance.":
      "4. If possible, alert others nearby for assistance.",
  "Manage Your Meals": "Manage Your Meals",
  "Meal Name": "Meal Name",
  "Enter meal name": "Enter meal name",
  "Meal Time": "Meal Time",
  "Tap to pick time": "Tap to pick time",
  "Description": "Description",
  "Short description": "Short description",
  "Add Meal": "Add Meal",
  "Meal added successfully": "Meal added successfully",
  "Meals List": "Meals List",
  "Delete Meal": "Delete Meal",
  "Are you sure you want to delete this meal?":
      "Are you sure you want to delete this meal?",
  "Cancel": "Cancel",
  "Delete": "Delete",
  "Manage Your Medications": "Manage Your Medications",
  "Medication Name": "Medication Name",
  "Enter medication name": "Enter medication name",
  "Dose (e.g. 500mg)": "Dose (e.g. 500mg)",
  "Enter dose": "Enter dose",
  "Time to Take": "Time to Take",
  "e.g. Morning, Evening": "e.g. Morning, Evening",
  "Add Medication": "Add Medication",
  "Medication added successfully": "Medication added successfully",
  "Medications List": "Medications List",
  "No medications added yet.": "No medications added yet.",
  "Privacy Policy": "Privacy Policy",
  "Your Privacy Matters": "Your Privacy Matters",
  "We are committed to protecting your privacy. This Privacy Policy outlines how we collect, use, and safeguard your information.":
      "We are committed to protecting your privacy. This Privacy Policy outlines how we collect, use, and safeguard your information.",
  "1. Information Collection": "1. Information Collection",
  "We collect data you provide, such as your name, email, and health information, to improve your experience.":
      "We collect data you provide, such as your name, email, and health information, to improve your experience.",
  "2. How We Use Your Data": "2. How We Use Your Data",
  "Your data is used solely for enhancing the features of the app, ensuring personalized content and support.":
      "Your data is used solely for enhancing the features of the app, ensuring personalized content and support.",
  "3. Data Protection": "3. Data Protection",
  "We implement strict security measures to ensure the safety of your personal data.":
      "We implement strict security measures to ensure the safety of your personal data.",
  "4. Your Consent": "4. Your Consent",
  "By using our app, you consent to this Privacy Policy.":
      "By using our app, you consent to this Privacy Policy.",
  "5. Changes to Policy": "5. Changes to Policy",
  "We may update this policy periodically. Please review it regularly for changes.":
      "We may update this policy periodically. Please review it regularly for changes.",
  "Personal Account Settings": "Personal Account Settings",
  "Full Name": "Full Name",
  "Enter your full name": "Enter your full name",
  "Email Address": "Email Address",
  "Enter your email address": "Enter your email address",
  "Phone Number": "Phone Number",
  "Enter your phone number": "Enter your phone number",
  "Change Password": "Change Password",
  "Update your account password": "Update your account password",
  "Deactivate Account": "Deactivate Account",
  "Temporarily deactivate your account": "Temporarily deactivate your account",
  "Save Changes": "Save Changes",
  "Current Password": "Current Password",
  "Enter current password": "Enter current password",
  "New Password": "New Password",
  "Enter new password": "Enter new password",
  "Confirm New Password": "Confirm New Password",
  "Confirm new password": "Confirm new password",
  "Update Password": "Update Password",
  "Password updated successfully": "Password updated successfully",
  "Passwords do not match": "Passwords do not match",
  "Reactivate Account": "Reactivate Account",
  "Are you sure?": "Are you sure?",
  "Your account will be temporarily deactivated.":
      "Your account will be temporarily deactivated.",
  "Deactivate": "Deactivate",
  "Account deactivated": "Account deactivated",
  "Do you want to reactivate your account?":
      "Do you want to reactivate your account?",
  "Reactivate": "Reactivate",
  "Account reactivated": "Account reactivated",
  "Are you sure you want to deactivate your account?":
      "Are you sure you want to deactivate your account?",
  "This will temporarily disable your account and you won't be able to access any features until you reactivate it.":
      "This will temporarily disable your account and you won't be able to access any features until you reactivate it.",
  "Child's Personal Profile": "Child's Personal Profile",
  "Child's Full Name": "Child's Full Name",
  "Enter child's full name": "Enter child's full name",
  "Date of Birth": "Date of Birth",
  "Enter child's date of birth": "Enter child's date of birth",
  "Select gender": "Select gender",
  "Select Gender": "Select Gender",
  "Child's Profile Link": "Child's Profile Link",
  "Enter child's profile link": "Enter child's profile link",
  "Link copied to clipboard": "Link copied to clipboard",
  "Profile updated successfully": "Profile updated successfully",
  "Who am i?": "Who am I?",
  "Parent": "Parent",
  "Caregiver": "Caregiver",
  "Please choose one of them": "Please choose one of them",
  "Ok": "OK",
  "Parents": "Parents",
  "Input glucose level before activity": "Input glucose level before activity",
  "Input glucose level after activity": "Input glucose level after activity",
  "Duration of the activity": "Duration of the activity",
  "Minutes": "Minutes",
  "High intensity exercises": "High intensity exercises",
  "Average running": "Average running",
  "Light walking": "Light walking",
  "Calculate": "Calculate",
  "Weight(Kg)": "Weight(Kg)",
  "Type of activity (MET)": "Type of activity (MET)",
  "Insulin Reduction": "Insulin Reduction",
  "Glucose Reduction Percentage": "Glucose Reduction Percentage",
  "Carbohydrates needed (grams)": "Carbohydrates needed (grams)",
  "Back to home": "Back to home",
};
